name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        # Aggiorna i pacchetti
        sudo apt update

        # Installa le dipendenze essenziali
        sudo apt install -y python3-pip openjdk-8-jdk git zlib1g-dev libncurses5 libffi-dev libssl-dev liblzma-dev
        sudo apt install -y build-essential autoconf libtool pkg-config cython3

        # Installa Cython e Buildozer tramite pip
        pip install cython
        pip install buildozer

    - name: Initialize Buildozer and Force Android SDK Installation
      run: |
        # Forza Buildozer a scaricare SDK e NDK Android
        buildozer -v android debug
      env:
        ANDROID_NDK_HOME: /opt/android/android-ndk
        ANDROID_SDK_ROOT: /opt/android/sdk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ContaMetriApp
        path: bin/*
